# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RegistrationService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RegistrationService.proto',
  package='egt.registration.v2.com',
  syntax='proto3',
  serialized_options=_b('\n&com.egt.client.registration.api.v2.comP\001ZFgitlab.egt-ua.loc/apis/gen/user-management/registration-service/v2/com'),
  serialized_pb=_b('\n\x19RegistrationService.proto\x12\x17\x65gt.registration.v2.com\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"y\n\x1cRegisterClientByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x38\n\rcommon_fields\x18\x03 \x01(\x0b\x32!.egt.registration.v2.CommonFields\"C\n\"SendRegistrationCodeToPhoneRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0e\n\x06locale\x18\x02 \x01(\t\"%\n#SendRegistrationCodeToPhoneResponse\"\x87\x01\n\x1cRegisterClientByPhoneRequest\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x38\n\rcommon_fields\x18\x04 \x01(\x0b\x32!.egt.registration.v2.CommonFields\"P\n\x16RegisterClientResponse\x12\x36\n\x12\x63lient_create_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xb2\x03\n\x13RegistrationService\x12\x7f\n\x15RegisterClientByEmail\x12\x35.egt.registration.v2.com.RegisterClientByEmailRequest\x1a/.egt.registration.v2.com.RegisterClientResponse\x12\x98\x01\n\x1bSendRegistrationCodeToPhone\x12;.egt.registration.v2.com.SendRegistrationCodeToPhoneRequest\x1a<.egt.registration.v2.com.SendRegistrationCodeToPhoneResponse\x12\x7f\n\x15RegisterClientByPhone\x12\x35.egt.registration.v2.com.RegisterClientByPhoneRequest\x1a/.egt.registration.v2.com.RegisterClientResponseBr\n&com.egt.client.registration.api.v2.comP\x01ZFgitlab.egt-ua.loc/apis/gen/user-management/registration-service/v2/comb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,])




_REGISTERCLIENTBYEMAILREQUEST = _descriptor.Descriptor(
  name='RegisterClientByEmailRequest',
  full_name='egt.registration.v2.com.RegisterClientByEmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='egt.registration.v2.com.RegisterClientByEmailRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='egt.registration.v2.com.RegisterClientByEmailRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='common_fields', full_name='egt.registration.v2.com.RegisterClientByEmailRequest.common_fields', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=222,
)


_SENDREGISTRATIONCODETOPHONEREQUEST = _descriptor.Descriptor(
  name='SendRegistrationCodeToPhoneRequest',
  full_name='egt.registration.v2.com.SendRegistrationCodeToPhoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='egt.registration.v2.com.SendRegistrationCodeToPhoneRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locale', full_name='egt.registration.v2.com.SendRegistrationCodeToPhoneRequest.locale', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=291,
)


_SENDREGISTRATIONCODETOPHONERESPONSE = _descriptor.Descriptor(
  name='SendRegistrationCodeToPhoneResponse',
  full_name='egt.registration.v2.com.SendRegistrationCodeToPhoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=330,
)


_REGISTERCLIENTBYPHONEREQUEST = _descriptor.Descriptor(
  name='RegisterClientByPhoneRequest',
  full_name='egt.registration.v2.com.RegisterClientByPhoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='egt.registration.v2.com.RegisterClientByPhoneRequest.phone', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='egt.registration.v2.com.RegisterClientByPhoneRequest.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='egt.registration.v2.com.RegisterClientByPhoneRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='common_fields', full_name='egt.registration.v2.com.RegisterClientByPhoneRequest.common_fields', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=468,
)


_REGISTERCLIENTRESPONSE = _descriptor.Descriptor(
  name='RegisterClientResponse',
  full_name='egt.registration.v2.com.RegisterClientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_create_time', full_name='egt.registration.v2.com.RegisterClientResponse.client_create_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=470,
  serialized_end=550,
)

_REGISTERCLIENTBYEMAILREQUEST.fields_by_name['common_fields'].message_type = common__pb2._COMMONFIELDS
_REGISTERCLIENTBYPHONEREQUEST.fields_by_name['common_fields'].message_type = common__pb2._COMMONFIELDS
_REGISTERCLIENTRESPONSE.fields_by_name['client_create_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['RegisterClientByEmailRequest'] = _REGISTERCLIENTBYEMAILREQUEST
DESCRIPTOR.message_types_by_name['SendRegistrationCodeToPhoneRequest'] = _SENDREGISTRATIONCODETOPHONEREQUEST
DESCRIPTOR.message_types_by_name['SendRegistrationCodeToPhoneResponse'] = _SENDREGISTRATIONCODETOPHONERESPONSE
DESCRIPTOR.message_types_by_name['RegisterClientByPhoneRequest'] = _REGISTERCLIENTBYPHONEREQUEST
DESCRIPTOR.message_types_by_name['RegisterClientResponse'] = _REGISTERCLIENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterClientByEmailRequest = _reflection.GeneratedProtocolMessageType('RegisterClientByEmailRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCLIENTBYEMAILREQUEST,
  '__module__' : 'RegistrationService_pb2'
  # @@protoc_insertion_point(class_scope:egt.registration.v2.com.RegisterClientByEmailRequest)
  })
_sym_db.RegisterMessage(RegisterClientByEmailRequest)

SendRegistrationCodeToPhoneRequest = _reflection.GeneratedProtocolMessageType('SendRegistrationCodeToPhoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDREGISTRATIONCODETOPHONEREQUEST,
  '__module__' : 'RegistrationService_pb2'
  # @@protoc_insertion_point(class_scope:egt.registration.v2.com.SendRegistrationCodeToPhoneRequest)
  })
_sym_db.RegisterMessage(SendRegistrationCodeToPhoneRequest)

SendRegistrationCodeToPhoneResponse = _reflection.GeneratedProtocolMessageType('SendRegistrationCodeToPhoneResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDREGISTRATIONCODETOPHONERESPONSE,
  '__module__' : 'RegistrationService_pb2'
  # @@protoc_insertion_point(class_scope:egt.registration.v2.com.SendRegistrationCodeToPhoneResponse)
  })
_sym_db.RegisterMessage(SendRegistrationCodeToPhoneResponse)

RegisterClientByPhoneRequest = _reflection.GeneratedProtocolMessageType('RegisterClientByPhoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCLIENTBYPHONEREQUEST,
  '__module__' : 'RegistrationService_pb2'
  # @@protoc_insertion_point(class_scope:egt.registration.v2.com.RegisterClientByPhoneRequest)
  })
_sym_db.RegisterMessage(RegisterClientByPhoneRequest)

RegisterClientResponse = _reflection.GeneratedProtocolMessageType('RegisterClientResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERCLIENTRESPONSE,
  '__module__' : 'RegistrationService_pb2'
  # @@protoc_insertion_point(class_scope:egt.registration.v2.com.RegisterClientResponse)
  })
_sym_db.RegisterMessage(RegisterClientResponse)


DESCRIPTOR._options = None

_REGISTRATIONSERVICE = _descriptor.ServiceDescriptor(
  name='RegistrationService',
  full_name='egt.registration.v2.com.RegistrationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=553,
  serialized_end=987,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterClientByEmail',
    full_name='egt.registration.v2.com.RegistrationService.RegisterClientByEmail',
    index=0,
    containing_service=None,
    input_type=_REGISTERCLIENTBYEMAILREQUEST,
    output_type=_REGISTERCLIENTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendRegistrationCodeToPhone',
    full_name='egt.registration.v2.com.RegistrationService.SendRegistrationCodeToPhone',
    index=1,
    containing_service=None,
    input_type=_SENDREGISTRATIONCODETOPHONEREQUEST,
    output_type=_SENDREGISTRATIONCODETOPHONERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterClientByPhone',
    full_name='egt.registration.v2.com.RegistrationService.RegisterClientByPhone',
    index=2,
    containing_service=None,
    input_type=_REGISTERCLIENTBYPHONEREQUEST,
    output_type=_REGISTERCLIENTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REGISTRATIONSERVICE)

DESCRIPTOR.services_by_name['RegistrationService'] = _REGISTRATIONSERVICE

# @@protoc_insertion_point(module_scope)
